# load packages
p_needed <- c("AER",
              "arm",
              "broom.helpers",
              "broom.mixed",
              "broom",
              "colorspace",
              "corrr",
              "cowplot",
              "data.table",
              "DT",
              "emmeans",
              "estimatr",
              "gdata",
              "ggcorrplot",
              "ggtext",
              "ggh4x",
              "ggrepel",
              "ggthemes",
              "grid",
              "gridExtra",
              "gt",
              "gtExtras",
              "haven",
              "htmltools",
              "infer",
              "irr", # for kripp.alpha
              "janitor",
              "labelled",
              "lme4",
              "lubridate",
              "magrittr",
              "margins",
              "marginaleffects",
              "modelsummary",
              "naniar",
              "plotly",
              "RColorBrewer",
              "readxl",
              "reshape2",
              "rlang",
              "rmarkdown",
              "scales",
              "sjlabelled",
              "stargazer",
              "texreg",
              "viridis",
              "writexl",
              "xtable",
              "tidyverse",
              "patchwork"
)

pacman::p_load(char = p_needed)
