# load packages
p_needed <- c("broom",
              "broom.helpers",
              "broom.mixed",
              "colorspace",
              "emmeans",
              "estimatr",
              "ggrepel",
              "ggtext",
              "ggh4x",
              "glue",
              "grid",
              "gt",
              "gtExtras",
              "haven",
              "htmltools",
              "infer",
              "janitor",
              "kableExtra",
              "knitr",
              "labelled",
              "lme4",
              "magrittr",
              "marginaleffects",
              "modelsummary",
              "patchwork",
              "readxl",
              "rlang",
              "scales",
              "survey",
              "texreg",
              "tidyverse",
              "viridis",
              "writexl",
              "xtable",
              "webshot",
              "webshot2"
              # packages not used in the other scripts:
              # "AER",
              # "arm",
              # "corrr",
              # "cowplot",
              # "data.table",
              # "DT",
              # "gdata",
              # "ggcorrplot",
              # "ggh4x",
              # "ggthemes",
              # "gridExtra",
              # "irr", # for kripp.alpha
              # "lubridate",
              # "margins",
              # "naniar",
              # "plotly",
              # "RColorBrewer",
              # "reshape2",
              # "rmarkdown",
              # "rnaturalearth",
              # "sf",
              # "sjlabelled",
              # "stargazer"
)

install.packages("pacman")
pacman::p_load(char = p_needed)
